GET https://rkanik.deno.dev/api/v1/users HTTP/1.1

###

POST https://rkanik.deno.dev/api/v1/users HTTP/1.1
content-type: application/json

{
   "name": "RK Anik",
   "email": "rkanik.me@gmail.com",
   "password": "12345678"
}

###

DELETE https://rkanik.deno.dev/api/v1/users HTTP/1.1