GET http://localhost:8000/api/v1/todos HTTP/1.1
headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6NCwibmFtZSI6IlJLIEFuaWsiLCJlbWFpbCI6InJrYW5pay5tZUBnbWFpbC5jb20iLCJleHAiOjE3NTM3OTEwNjZ9.S2RJx66feA0flcVUGhctuw8bPSqfMkaCeroM9SE1xZA

###

GET http://localhost:8000/api/v1/todos/2605debf-60df-4bdc-9f22-c0fb4cae90f6 HTTP/1.1

###

POST http://localhost:8000/api/v1/todos HTTP/1.1
content-type: application/json
headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6NCwibmFtZSI6IlJLIEFuaWsiLCJlbWFpbCI6InJrYW5pay5tZUBnbWFpbC5jb20iLCJleHAiOjE3NTM3OTEwNjZ9.S2RJx66feA0flcVUGhctuw8bPSqfMkaCeroM9SE1xZA

{
   "title": "Build a todo app with NextJS"
}

###

POST http://localhost:8000/api/v1/todos HTTP/1.1
content-type: application/json

{
   "id": "2605debf-60df-4bdc-9f22-c0fb4cae90f6",
   "title": "Build a todo app with Deno",
   "completed": false
}

###

PATCH http://localhost:8000/api/v1/todos/2605debf-60df-4bdc-9f22-c0fb4cae90f6 HTTP/1.1
content-type: application/json

{
   "id": "2605debf-60df-4bdc-9f22-c0fb4cae90f6",
   "title": "Build a todo app with Deno",
   "completed": false
}

###

DELETE http://localhost:8000/api/v1/todos/25f4ff21-0ee5-43fd-82e2-44cded37c664 HTTP/1.1

###

DELETE http://localhost:8000/api/v1/todos HTTP/1.1
